import js from "@eslint/js";
import eslintPluginPrettier from "eslint-plugin-prettier/recommended";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "dist",
      ".output",
      ".vinxi",
      // Generated by the Supabase CLI and verified separately for drift.
      "src/backend/generated/**",
      // Raw Figma exports are reference material, never application source.
      "docs/engineering/pepites-v1.1-figma-notes/*.tsx",
      // Auto-generated by @lovable.dev/mcp-js — regenerated by the Vite plugin.
      "src/routes/mcp.ts",
      "src/routes/\\[.mcp\\]/**",
      "src/routes/\\[.well-known\\]/**",
      "src/routes/**/mcp.ts",
      "src/routes/**/list-tools.ts",
      "src/routes/**/invoke-tool/**",
      "src/routes/**/oauth-protected-resource.ts",
    ],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "server-only",
              message:
                "TanStack Start does not use the Next.js `server-only` package. Rename the module to `*.server.ts` or mark it with `@tanstack/react-start/server-only`.",
            },
          ],
        },
      ],
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  // Test files: narrow relaxations. Tests build partial mocks of Supabase and
  // service surfaces where `any`/`unknown` casts are unavoidable, and empty
  // catch blocks assert "throws" without needing the caught value.
  {
    files: ["src/**/*.test.ts", "src/**/*.test.tsx", "src/services/__test-shim.ts"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "no-empty": ["error", { allowEmptyCatch: true }],
    },
  },
  eslintPluginPrettier,
  {
    // Lovable owns this legacy schema's generated formatting.
    // Semantic lint and TypeScript checks still apply; authoritative types have a drift gate.
    files: ["src/integrations/supabase/types.ts"],
    rules: { "prettier/prettier": "off" },
  },
);
