// Regenerates src/brand.js from the product logo files (the single source of truth).
// Run from the repository root: node design-lab/manager-cards-claude/tools/gen-brand.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const brandDir = join(here, "../../../src/assets/brand");
const out = join(here, "../src/brand.js");

function read(name) {
  const svg = readFileSync(join(brandDir, name), "utf8");
  const viewBox = svg.match(/viewBox="([^"]+)"/)[1];
  const paths = [...svg.matchAll(/<path([^>]*)\/>/g)].map((m) => ({
    // st0 paths carry the logo colour; unclassed paths are the ball's panels.
    part: /class="st0"/.test(m[1]) ? "ink" : "ball",
    d: m[1].match(/d="([^"]+)"/)[1],
  }));
  return {
    viewBox,
    paths,
    dataUri: "data:image/svg+xml;base64," + Buffer.from(svg).toString("base64"),
  };
}

const brand = {
  wordmark: read("botolago-wordmark-color.svg"),
  wordmarkLight: read("botolago-wordmark-light.svg"),
  mark: read("botolago-mark-color.svg"),
  markLight: read("botolago-mark-light.svg"),
};
writeFileSync(
  out,
  "/* Generated by tools/gen-brand.mjs from src/assets/brand. Do not edit by hand. */\n" +
    "window.MC_BRAND = " +
    JSON.stringify(brand) +
    ";\n",
);
console.log("wrote", out);
