/**
 * Scoring proof: the SQL that records the three matches (prints it; runs nothing).
 *
 *   bun scripts/backend/scoring-proof/observations-sql.ts > observations.sql
 *
 * Match 1 goes through the reconciled ingestion (`api.service_record_reconciled_fantasy_observation`):
 * first a dry run that must keep nothing, then the write, then a retry that must store nothing new.
 * Matches 2 and 3 are recorded as reviewed corrections (a person's match sheet), the
 * existing path for a match no provider pair covers. STAGING OR LOCAL ONLY (same guard as world.sql).
 */
import { matchOneRequest, PROOF_ID } from "./match-1-request";

const prepared = await matchOneRequest();
if (!prepared.request) throw new Error(JSON.stringify(prepared.blockers));
const request = JSON.stringify(prepared.request);

process.stdout
  .write(`-- Generated by scripts/backend/scoring-proof/observations-sql.ts. Request digest ${prepared.requestDigest}.
do $$
begin
  if coalesce(current_setting('botolago.scoring_proof_environment', true), '') not in ('staging', 'local') then
    raise exception 'scoring_proof_requires_staging_or_local';
  end if;
  if not exists (select 1 from app.competitions where id = '${PROOF_ID("c", 2)}') then
    raise exception 'scoring_proof_world_missing';
  end if;
end $$;
select set_config('request.jwt.claims', '{"role":"service_role"}', true);

select set_config('scoring_proof.match1', $req$${request}$req$, true) is not null as request_loaded;
create temporary table proof_result (step text primary key, value jsonb) on commit drop;
insert into proof_result values ('observations_before',
  to_jsonb((select count(*) from app_private.fantasy_fixture_observations where fixture_id::text like 'fb5c0000-%')));
insert into proof_result values ('match1_dry_run', api.service_record_reconciled_fantasy_observation(
  '${PROOF_ID("f", 1)}', current_setting('scoring_proof.match1')::jsonb, true));
insert into proof_result values ('observations_after_dry_run',
  to_jsonb((select count(*) from app_private.fantasy_fixture_observations where fixture_id::text like 'fb5c0000-%')));
insert into proof_result values ('match1_record', api.service_record_reconciled_fantasy_observation(
  '${PROOF_ID("f", 1)}', current_setting('scoring_proof.match1')::jsonb));
insert into proof_result values ('match1_retry', api.service_record_reconciled_fantasy_observation(
  '${PROOF_ID("f", 1)}', current_setting('scoring_proof.match1')::jsonb));

-- Matches 2 and 3: a reviewed match sheet. Every player 90 minutes; the 12th player of club 3 did not play.
create function pg_temp.sheet_row(n integer, team integer, conceded integer, extra jsonb) returns jsonb language sql as $f$
  select jsonb_build_object('playerId', ('fb5c0000-0000-4000-8000-e' || lpad(n::text, 11, '0'))::uuid,
    'teamId', ('fb5c0000-0000-4000-8000-d' || lpad(team::text, 11, '0'))::uuid, 'started', true,
    'stats', jsonb_build_object('minutes', 90, 'goals', 0, 'assists', 0, 'cleanSheet', conceded = 0, 'goalsConceded', conceded,
      'saves', 0, 'penaltiesSaved', 0, 'penaltiesMissed', 0, 'yellowCards', 0, 'redCards', 0,
      'secondYellowDismissals', 0, 'ownGoals', 0) || extra,
    'evidence', (select jsonb_object_agg(field, jsonb_build_object('state', 'verified', 'source', 'scoring-proof-match-sheet',
      'observedAt', '2026-08-20T21:00:00Z', 'references', jsonb_build_array('scoring-proof:sheet:' || team)))
      from unnest(array['minutes','goals','assists','cleanSheet','goalsConceded','saves','penaltiesSaved','penaltiesMissed',
        'yellowCards','redCards','secondYellowDismissals','ownGoals']) field))
$f$;
create function pg_temp.sheet(home_score integer, away_score integer, rows jsonb, absent jsonb) returns jsonb language sql as $f$
  select jsonb_build_object('homeScore', home_score, 'awayScore', away_score, 'anonymousStarters', 0, 'anonymousByTeam', '{}'::jsonb,
    'references', jsonb_build_array('scoring-proof:match-sheet'), 'participationComplete', true, 'disciplineComplete', true,
    'verifiedNonParticipants', absent, 'players', rows,
    'reason', 'Scoring proof: synthetic reviewed match sheet (staging only).', 'reviewer', 'scoring-proof', 'expectedDigest', null)
$f$;
insert into proof_result values ('match2_record', api.service_record_fantasy_observation('${PROOF_ID("f", 2)}',
  pg_temp.sheet(0, 0,
    (select jsonb_agg(pg_temp.sheet_row(n, case when n <= 33 then 3 else 4 end, 0,
       case when n = 23 then '{"saves":4}'::jsonb else '{}'::jsonb end) order by n) from generate_series(23, 44) n),
    jsonb_build_array('${PROOF_ID("e", 67)}')),
  'reviewed-correction'));
insert into proof_result values ('match3_record', api.service_record_fantasy_observation('${PROOF_ID("f", 3)}',
  pg_temp.sheet(1, 0,
    (select jsonb_agg(pg_temp.sheet_row(n, case when n <= 55 then 5 else 6 end, case when n <= 55 then 0 else 1 end,
       case n when 54 then '{"goals":1}'::jsonb when 50 then '{"assists":1}'::jsonb when 57 then '{"yellowCards":1}'::jsonb
         else '{}'::jsonb end) order by n) from generate_series(45, 66) n),
    '[]'::jsonb),
  'reviewed-correction'));
select jsonb_object_agg(step, value) as scoring_proof_observations from proof_result;
`);
