/**
 * The response `/fantasy/rules` received from production's `api.fantasy_rules`
 * on 2026-10-07 (season 2026/27, ruleset `botolago-fantasy-v1.1`), read by the
 * page itself through the public key. Kept verbatim, in the server's order.
 */
export const PRODUCTION_RULES = {
  budget: 100,
  deadline: { gracePeriodSeconds: 0, minutesBeforeFirstFixture: 90 },
  seasonId: "5ada3e98-2929-405a-a3f1-a26de8e51933",
  rulesetId: "f6100000-0000-4000-8000-000000000101",
  squadSize: 15,
  rulesetCode: "botolago-fantasy-v1.1",
  rulesetVersion: 1,
  transferHitCost: 4,
  captainMultiplier: 2,
  maxPlayersPerClub: 3,
  initialFreeTransfers: 1,
  rulesetSemanticVersion: "1.1",
  maxFreeTransferRollover: 2,
  tripleCaptainMultiplier: 3,
  positions: [
    {
      code: "GK",
      goalPoints: 10,
      squadQuota: 2,
      startingMaximum: 1,
      startingMinimum: 1,
      cleanSheetPoints: 4,
    },
    {
      code: "DEF",
      goalPoints: 6,
      squadQuota: 5,
      startingMaximum: 5,
      startingMinimum: 3,
      cleanSheetPoints: 4,
    },
    {
      code: "MID",
      goalPoints: 5,
      squadQuota: 5,
      startingMaximum: 5,
      startingMinimum: 2,
      cleanSheetPoints: 1,
    },
    {
      code: "FWD",
      goalPoints: 4,
      squadQuota: 3,
      startingMaximum: 3,
      startingMinimum: 1,
      cleanSheetPoints: 0,
    },
  ],
  chips: [
    {
      chipType: "bench_boost",
      cancellable: false,
      allocationCode: "bench_boost",
      endsAtGameweek: null,
      startsAtGameweek: 1,
    },
    {
      chipType: "free_hit",
      cancellable: false,
      allocationCode: "free_hit",
      endsAtGameweek: null,
      startsAtGameweek: 1,
    },
    {
      chipType: "triple_captain",
      cancellable: false,
      allocationCode: "triple_captain",
      endsAtGameweek: null,
      startsAtGameweek: 1,
    },
    {
      chipType: "wildcard",
      cancellable: false,
      allocationCode: "wildcard_1",
      endsAtGameweek: 15,
      startsAtGameweek: 1,
    },
    {
      chipType: "wildcard",
      cancellable: false,
      allocationCode: "wildcard_2",
      endsAtGameweek: null,
      startsAtGameweek: 16,
    },
  ],
  features: {
    bonus_points_enabled: false,
    official_assists_only: true,
    player_of_match_enabled: false,
    inferred_assists_enabled: false,
    fixture_difficulty_enabled: true,
  },
  scoring: [
    { points: 2, category: "appearance_full", position: null, threshold: 60 },
    { points: 1, category: "appearance_short", position: null, threshold: 1 },
    { points: -3, category: "direct_red_card", position: null, threshold: null },
    { points: -1, category: "goals_conceded", position: "DEF", threshold: 2 },
    { points: -1, category: "goals_conceded", position: "GK", threshold: 2 },
    { points: 3, category: "official_assist", position: null, threshold: null },
    { points: -2, category: "own_goal", position: null, threshold: null },
    { points: -2, category: "penalty_miss", position: null, threshold: null },
    { points: 5, category: "penalty_save", position: "GK", threshold: null },
    { points: 1, category: "saves", position: "GK", threshold: 3 },
    { points: -3, category: "second_yellow_dismissal", position: null, threshold: null },
    { points: -1, category: "yellow_card", position: null, threshold: null },
  ],
};
