-- ============================================================================
-- BotolaGO Production V2 (tkewgajrljbwgwedqsxn)
-- Launch fixes of 2026-09-24 -- the database half.
--
-- GENERATED by scripts/backend/assemble-apply-launch-fixes.py from
-- scripts/backend/templates/apply-launch-fixes.{head,tail}.sql and the
-- migration files it embeds. Do not edit this file by hand: edit a template
-- or a migration and re-assemble (the bun test fails when they drift).
--
-- HOW TO RUN
--   1. GitHub -> Actions: make sure "Fantasy season orchestrator" is not
--      running right now (nothing yellow). No other database work either.
--   2. Supabase dashboard -> project "BotolaGO Production V2" -> SQL Editor ->
--      New query. Paste this WHOLE file and press Run.
--      As shipped it is a REHEARSAL: every change is applied inside one
--      transaction, checked, summarised, and then thrown away. It ends with a
--      red box that starts "REHEARSAL PASSED -- nothing was saved"; its
--      DETAIL lists exactly what applying would change.
--   3. If the DETAIL reads as expected, change REHEARSAL to APPLY on the
--      line marked "MODE" below and press Run again. The last row then says
--      "Applied".
--   If any check fails, the script stops with a message saying what, and
--   nothing is saved. Do not edit a check to make it pass: a check firing
--   means the database is not in the state this script was built against.
--
-- WHAT IT DOES
--   * refuses to run twice, or on a database that is not at the migration
--     history and function bodies this batch was reviewed against;
--   * applies each migration file exactly as it is in the repository and
--     records it in supabase_migrations.schema_migrations (the whole file as
--     statements[1]);
--   * brings the Fantasy season up to the new rule with the same service
--     calls the season orchestrator makes (calendar sync, then the lifecycle
--     for any open gameweek past its deadline);
--   * checks the result and summarises it, including how long the /matches
--     page's database call now takes (1,025 ms when the audit measured it)
--     and the related-articles rail under a news article (608-644 ms);
--   * leaves live scores switched off, but ready to call every 2 minutes
--     during a match once switched on (docs/backend/EMAIL_NOTIFICATIONS.md);
--   * makes article "last modified" dates truthful (sitemap, search data);
--   * adds the health checks, the (switched-off) failure alerts and the
--     endpoint where visitors' browsers report errors, without who they are
--     (docs/operations/ALERTS.md).
--   Lock and statement timeouts are bounded, so it gives up rather than queue
--   behind a long-running transaction on the live site.
-- ============================================================================

begin;

set local lock_timeout = '5s';
set local statement_timeout = '120s';

-- MODE: REHEARSAL (as shipped) or APPLY.
select set_config('botolago.launch_fixes_mode', 'REHEARSAL', true);

-- The migrations this batch applies, in order.
select set_config('botolago.batch_versions', '@@BATCH_VERSIONS@@', true);

-- ---------------------------------------------------------------------------
-- Preflight: the database must be exactly where this batch was reviewed.
-- ---------------------------------------------------------------------------
do $preflight$
declare
  problems text[] := '{}';
  expected record;
  actual text;
begin
  if to_regclass('supabase_migrations.schema_migrations') is null then
    raise exception 'stop: supabase_migrations.schema_migrations does not exist -- is this the BotolaGO database?';
  end if;
  if exists (
    select 1 from supabase_migrations.schema_migrations
    where version in (select unnest(string_to_array(current_setting('botolago.batch_versions', true), ',')))
  ) then
    raise exception 'stop: part of this batch is already recorded as applied -- find out why before going on';
  end if;
  if (select max(version) from supabase_migrations.schema_migrations) <> '20260924190100' then
    raise exception 'stop: the latest applied migration is %, not 20260924190100 -- this batch was built on 20260924190100',
      (select max(version) from supabase_migrations.schema_migrations);
  end if;
  if to_regprocedure('app_private.fantasy_enrolment_gameweek(uuid)') is not null then
    raise exception 'stop: app_private.fantasy_enrolment_gameweek already exists, but the migration is not recorded';
  end if;
  if to_regclass('app_private.fantasy_lifecycle_heartbeat') is not null
    or exists (select 1 from cron.job where jobname = 'fantasy-lifecycle-tick') then
    raise exception 'stop: the Fantasy lifecycle tick already exists, but the migration is not recorded';
  end if;
  if to_regclass('app_private.ops_alert_state') is not null
    or exists (select 1 from cron.job where jobname = 'ops-alert-tick') then
    raise exception 'stop: the ops alert tick already exists, but the migration is not recorded';
  end if;
  if to_regclass('app_private.client_error_counts') is not null
    or to_regprocedure('api.report_client_errors(jsonb)') is not null then
    raise exception 'stop: the browser error reports already exist, but the migration is not recorded';
  end if;
  if to_regclass('app_private.timezone_names') is not null
    or to_regprocedure('app_private.is_valid_timezone(text)') is not null then
    raise exception 'stop: the timezone snapshot already exists, but the migration is not recorded';
  end if;
  if to_regclass('app_private.football_live_refresh_heartbeat') is not null then
    raise exception 'stop: the live refresh heartbeat already exists, but the migration is not recorded';
  end if;
  if (select schedule from cron.job where jobname = 'football-live-refresh') is distinct from '*/15 * * * *' then
    raise exception 'stop: the football-live-refresh job is not on its reviewed 15-minute schedule';
  end if;

  -- The functions this batch replaces must still be the bodies it was
  -- reviewed against (measured on production, 2026-09-24). One may already
  -- carry this batch's own body (`applied_early`): api.news_related_articles
  -- from 20260924200400 went live on its own on 2026-09-25 at 06:33 UTC,
  -- while Google's crawl of the news articles had the database overloaded.
  -- The text is identical; this batch re-creates it and records the
  -- migration.
  for expected in
    select * from (values
      ('api.service_sync_fantasy_calendar(uuid)', '023f32515cb970a265235fb9a158732d', null::text),
      ('api.service_advance_fantasy_lifecycle(uuid,bigint,integer)', '86d667920c3e5be4e63d3890bdc789c8', null),
      ('api.service_prepare_next_fantasy_gameweek(uuid,uuid,bigint,integer)', '98d18a8eed916af8cea3ed453e03f23f', null),
      ('api.create_fantasy_team(uuid,uuid,text,jsonb,uuid)', 'd0c4cfd5c1a9290a8805ea8395ecd82e', null),
      ('api.fantasy_hub(text)', '7278bb93007935facc742ce19a4d6277', null),
      ('api.service_fantasy_deadline_watch(uuid,integer,integer)', '7d9b32bb45f2fe565ad38a47c1f6db98', null),
      ('api.football_matches_by_date(date,text,text,text[],uuid,uuid,timestamp with time zone,uuid,integer)', '3530bc9042d16dac749af5541c826ad0', null),
      ('app_private.assert_valid_timezone(text)', 'ff87c87f861e83fff25f6d28d8d49468', null),
      ('api.news_related_articles(uuid,integer)', '29756c378f2dbd2a287aa50bea99614c', '51d1a8a990469b2467a49dd0f2447d74'),
      ('app_private.football_live_refresh_tick()', '0301db9dbaee6ba9324acd579d59bfc0', null),
      ('api.news_article_detail(text,text)', 'f794fedd2b5bd8c793181c14617648e7', null),
      ('api.news_sitemap_entries(integer)', 'f901508e07445cb7050069869cee6bfa', null)
    ) as t(signature, md5, applied_early)
  loop
    if to_regprocedure(expected.signature) is null then
      problems := problems || (expected.signature || ' is missing');
      continue;
    end if;
    actual := md5(pg_get_functiondef(to_regprocedure(expected.signature)));
    if actual <> expected.md5 and actual is distinct from expected.applied_early then
      problems := problems || (expected.signature || ' changed since review (md5 ' || actual || ')');
    end if;
  end loop;

  if cardinality(problems) > 0 then
    raise exception 'stop: the database is not what this batch was reviewed against: %', problems;
  end if;
end
$preflight$;

