/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NewsRouteImport } from './routes/news'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as FantasyRouteImport } from './routes/fantasy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FantasyIndexRouteImport } from './routes/fantasy.index'
import { Route as NewsArticleIdRouteImport } from './routes/news.$articleId'
import { Route as MatchesMatchIdRouteImport } from './routes/matches.$matchId'
import { Route as FantasyTransfersRouteImport } from './routes/fantasy.transfers'
import { Route as FantasyTopPlayersRouteImport } from './routes/fantasy.top-players'
import { Route as FantasyTeamRouteImport } from './routes/fantasy.team'
import { Route as FantasyRulesRouteImport } from './routes/fantasy.rules'
import { Route as FantasyPointsRouteImport } from './routes/fantasy.points'
import { Route as FantasyPlayersRouteImport } from './routes/fantasy.players'
import { Route as FantasyLeaguesRouteImport } from './routes/fantasy.leagues'
import { Route as FantasyFixturesRouteImport } from './routes/fantasy.fixtures'
import { Route as FantasyCreateRouteImport } from './routes/fantasy.create'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as AuthUpdatePasswordRouteImport } from './routes/auth.update-password'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthProfileSetupRouteImport } from './routes/auth.profile-setup'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminApprovalsRouteImport } from './routes/admin.approvals'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as FantasyPlayersPlayerIdRouteImport } from './routes/fantasy.players.$playerId'
import { Route as FantasyLeaguesLeagueIdRouteImport } from './routes/fantasy.leagues.$leagueId'
import { Route as AdminStaffPrincipalIdRouteImport } from './routes/admin.staff.$principalId'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const FantasyRoute = FantasyRouteImport.update({
  id: '/fantasy',
  path: '/fantasy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FantasyIndexRoute = FantasyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FantasyRoute,
} as any)
const NewsArticleIdRoute = NewsArticleIdRouteImport.update({
  id: '/$articleId',
  path: '/$articleId',
  getParentRoute: () => NewsRoute,
} as any)
const MatchesMatchIdRoute = MatchesMatchIdRouteImport.update({
  id: '/$matchId',
  path: '/$matchId',
  getParentRoute: () => MatchesRoute,
} as any)
const FantasyTransfersRoute = FantasyTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => FantasyRoute,
} as any)
const FantasyTopPlayersRoute = FantasyTopPlayersRouteImport.update({
  id: '/top-players',
  path: '/top-players',
  getParentRoute: () => FantasyRoute,
} as any)
const FantasyTeamRoute = FantasyTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => FantasyRoute,
} as any)
const FantasyRulesRoute = FantasyRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => FantasyRoute,
} as any)
const FantasyPointsRoute = FantasyPointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => FantasyRoute,
} as any)
const FantasyPlayersRoute = FantasyPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => FantasyRoute,
} as any)
const FantasyLeaguesRoute = FantasyLeaguesRouteImport.update({
  id: '/leagues',
  path: '/leagues',
  getParentRoute: () => FantasyRoute,
} as any)
const FantasyFixturesRoute = FantasyFixturesRouteImport.update({
  id: '/fixtures',
  path: '/fixtures',
  getParentRoute: () => FantasyRoute,
} as any)
const FantasyCreateRoute = FantasyCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => FantasyRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUpdatePasswordRoute = AuthUpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileSetupRoute = AuthProfileSetupRouteImport.update({
  id: '/profile-setup',
  path: '/profile-setup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AdminRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const FantasyPlayersPlayerIdRoute = FantasyPlayersPlayerIdRouteImport.update({
  id: '/$playerId',
  path: '/$playerId',
  getParentRoute: () => FantasyPlayersRoute,
} as any)
const FantasyLeaguesLeagueIdRoute = FantasyLeaguesLeagueIdRouteImport.update({
  id: '/$leagueId',
  path: '/$leagueId',
  getParentRoute: () => FantasyLeaguesRoute,
} as any)
const AdminStaffPrincipalIdRoute = AdminStaffPrincipalIdRouteImport.update({
  id: '/$principalId',
  path: '/$principalId',
  getParentRoute: () => AdminStaffRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/fantasy': typeof FantasyRouteWithChildren
  '/matches': typeof MatchesRouteWithChildren
  '/mcp': typeof McpRoute
  '/news': typeof NewsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/staff': typeof AdminStaffRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/profile-setup': typeof AuthProfileSetupRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/fantasy/create': typeof FantasyCreateRoute
  '/fantasy/fixtures': typeof FantasyFixturesRoute
  '/fantasy/leagues': typeof FantasyLeaguesRouteWithChildren
  '/fantasy/players': typeof FantasyPlayersRouteWithChildren
  '/fantasy/points': typeof FantasyPointsRoute
  '/fantasy/rules': typeof FantasyRulesRoute
  '/fantasy/team': typeof FantasyTeamRoute
  '/fantasy/top-players': typeof FantasyTopPlayersRoute
  '/fantasy/transfers': typeof FantasyTransfersRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/news/$articleId': typeof NewsArticleIdRoute
  '/fantasy/': typeof FantasyIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/staff/$principalId': typeof AdminStaffPrincipalIdRoute
  '/fantasy/leagues/$leagueId': typeof FantasyLeaguesLeagueIdRoute
  '/fantasy/players/$playerId': typeof FantasyPlayersPlayerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/matches': typeof MatchesRouteWithChildren
  '/mcp': typeof McpRoute
  '/news': typeof NewsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/staff': typeof AdminStaffRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/profile-setup': typeof AuthProfileSetupRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/fantasy/create': typeof FantasyCreateRoute
  '/fantasy/fixtures': typeof FantasyFixturesRoute
  '/fantasy/leagues': typeof FantasyLeaguesRouteWithChildren
  '/fantasy/players': typeof FantasyPlayersRouteWithChildren
  '/fantasy/points': typeof FantasyPointsRoute
  '/fantasy/rules': typeof FantasyRulesRoute
  '/fantasy/team': typeof FantasyTeamRoute
  '/fantasy/top-players': typeof FantasyTopPlayersRoute
  '/fantasy/transfers': typeof FantasyTransfersRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/news/$articleId': typeof NewsArticleIdRoute
  '/fantasy': typeof FantasyIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/staff/$principalId': typeof AdminStaffPrincipalIdRoute
  '/fantasy/leagues/$leagueId': typeof FantasyLeaguesLeagueIdRoute
  '/fantasy/players/$playerId': typeof FantasyPlayersPlayerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/fantasy': typeof FantasyRouteWithChildren
  '/matches': typeof MatchesRouteWithChildren
  '/mcp': typeof McpRoute
  '/news': typeof NewsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/staff': typeof AdminStaffRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/profile-setup': typeof AuthProfileSetupRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/fantasy/create': typeof FantasyCreateRoute
  '/fantasy/fixtures': typeof FantasyFixturesRoute
  '/fantasy/leagues': typeof FantasyLeaguesRouteWithChildren
  '/fantasy/players': typeof FantasyPlayersRouteWithChildren
  '/fantasy/points': typeof FantasyPointsRoute
  '/fantasy/rules': typeof FantasyRulesRoute
  '/fantasy/team': typeof FantasyTeamRoute
  '/fantasy/top-players': typeof FantasyTopPlayersRoute
  '/fantasy/transfers': typeof FantasyTransfersRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/news/$articleId': typeof NewsArticleIdRoute
  '/fantasy/': typeof FantasyIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/staff/$principalId': typeof AdminStaffPrincipalIdRoute
  '/fantasy/leagues/$leagueId': typeof FantasyLeaguesLeagueIdRoute
  '/fantasy/players/$playerId': typeof FantasyPlayersPlayerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/fantasy'
    | '/matches'
    | '/mcp'
    | '/news'
    | '/profile'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/approvals'
    | '/admin/audit'
    | '/admin/security'
    | '/admin/staff'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/profile-setup'
    | '/auth/register'
    | '/auth/update-password'
    | '/auth/verify'
    | '/fantasy/create'
    | '/fantasy/fixtures'
    | '/fantasy/leagues'
    | '/fantasy/players'
    | '/fantasy/points'
    | '/fantasy/rules'
    | '/fantasy/team'
    | '/fantasy/top-players'
    | '/fantasy/transfers'
    | '/matches/$matchId'
    | '/news/$articleId'
    | '/fantasy/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/staff/$principalId'
    | '/fantasy/leagues/$leagueId'
    | '/fantasy/players/$playerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/matches'
    | '/mcp'
    | '/news'
    | '/profile'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/approvals'
    | '/admin/audit'
    | '/admin/security'
    | '/admin/staff'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/profile-setup'
    | '/auth/register'
    | '/auth/update-password'
    | '/auth/verify'
    | '/fantasy/create'
    | '/fantasy/fixtures'
    | '/fantasy/leagues'
    | '/fantasy/players'
    | '/fantasy/points'
    | '/fantasy/rules'
    | '/fantasy/team'
    | '/fantasy/top-players'
    | '/fantasy/transfers'
    | '/matches/$matchId'
    | '/news/$articleId'
    | '/fantasy'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/staff/$principalId'
    | '/fantasy/leagues/$leagueId'
    | '/fantasy/players/$playerId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/fantasy'
    | '/matches'
    | '/mcp'
    | '/news'
    | '/profile'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/approvals'
    | '/admin/audit'
    | '/admin/security'
    | '/admin/staff'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/profile-setup'
    | '/auth/register'
    | '/auth/update-password'
    | '/auth/verify'
    | '/fantasy/create'
    | '/fantasy/fixtures'
    | '/fantasy/leagues'
    | '/fantasy/players'
    | '/fantasy/points'
    | '/fantasy/rules'
    | '/fantasy/team'
    | '/fantasy/top-players'
    | '/fantasy/transfers'
    | '/matches/$matchId'
    | '/news/$articleId'
    | '/fantasy/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/staff/$principalId'
    | '/fantasy/leagues/$leagueId'
    | '/fantasy/players/$playerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  FantasyRoute: typeof FantasyRouteWithChildren
  MatchesRoute: typeof MatchesRouteWithChildren
  McpRoute: typeof McpRoute
  NewsRoute: typeof NewsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fantasy': {
      id: '/fantasy'
      path: '/fantasy'
      fullPath: '/fantasy'
      preLoaderRoute: typeof FantasyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fantasy/': {
      id: '/fantasy/'
      path: '/'
      fullPath: '/fantasy/'
      preLoaderRoute: typeof FantasyIndexRouteImport
      parentRoute: typeof FantasyRoute
    }
    '/news/$articleId': {
      id: '/news/$articleId'
      path: '/$articleId'
      fullPath: '/news/$articleId'
      preLoaderRoute: typeof NewsArticleIdRouteImport
      parentRoute: typeof NewsRoute
    }
    '/matches/$matchId': {
      id: '/matches/$matchId'
      path: '/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof MatchesMatchIdRouteImport
      parentRoute: typeof MatchesRoute
    }
    '/fantasy/transfers': {
      id: '/fantasy/transfers'
      path: '/transfers'
      fullPath: '/fantasy/transfers'
      preLoaderRoute: typeof FantasyTransfersRouteImport
      parentRoute: typeof FantasyRoute
    }
    '/fantasy/top-players': {
      id: '/fantasy/top-players'
      path: '/top-players'
      fullPath: '/fantasy/top-players'
      preLoaderRoute: typeof FantasyTopPlayersRouteImport
      parentRoute: typeof FantasyRoute
    }
    '/fantasy/team': {
      id: '/fantasy/team'
      path: '/team'
      fullPath: '/fantasy/team'
      preLoaderRoute: typeof FantasyTeamRouteImport
      parentRoute: typeof FantasyRoute
    }
    '/fantasy/rules': {
      id: '/fantasy/rules'
      path: '/rules'
      fullPath: '/fantasy/rules'
      preLoaderRoute: typeof FantasyRulesRouteImport
      parentRoute: typeof FantasyRoute
    }
    '/fantasy/points': {
      id: '/fantasy/points'
      path: '/points'
      fullPath: '/fantasy/points'
      preLoaderRoute: typeof FantasyPointsRouteImport
      parentRoute: typeof FantasyRoute
    }
    '/fantasy/players': {
      id: '/fantasy/players'
      path: '/players'
      fullPath: '/fantasy/players'
      preLoaderRoute: typeof FantasyPlayersRouteImport
      parentRoute: typeof FantasyRoute
    }
    '/fantasy/leagues': {
      id: '/fantasy/leagues'
      path: '/leagues'
      fullPath: '/fantasy/leagues'
      preLoaderRoute: typeof FantasyLeaguesRouteImport
      parentRoute: typeof FantasyRoute
    }
    '/fantasy/fixtures': {
      id: '/fantasy/fixtures'
      path: '/fixtures'
      fullPath: '/fantasy/fixtures'
      preLoaderRoute: typeof FantasyFixturesRouteImport
      parentRoute: typeof FantasyRoute
    }
    '/fantasy/create': {
      id: '/fantasy/create'
      path: '/create'
      fullPath: '/fantasy/create'
      preLoaderRoute: typeof FantasyCreateRouteImport
      parentRoute: typeof FantasyRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/update-password': {
      id: '/auth/update-password'
      path: '/update-password'
      fullPath: '/auth/update-password'
      preLoaderRoute: typeof AuthUpdatePasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/profile-setup': {
      id: '/auth/profile-setup'
      path: '/profile-setup'
      fullPath: '/auth/profile-setup'
      preLoaderRoute: typeof AuthProfileSetupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fantasy/players/$playerId': {
      id: '/fantasy/players/$playerId'
      path: '/$playerId'
      fullPath: '/fantasy/players/$playerId'
      preLoaderRoute: typeof FantasyPlayersPlayerIdRouteImport
      parentRoute: typeof FantasyPlayersRoute
    }
    '/fantasy/leagues/$leagueId': {
      id: '/fantasy/leagues/$leagueId'
      path: '/$leagueId'
      fullPath: '/fantasy/leagues/$leagueId'
      preLoaderRoute: typeof FantasyLeaguesLeagueIdRouteImport
      parentRoute: typeof FantasyLeaguesRoute
    }
    '/admin/staff/$principalId': {
      id: '/admin/staff/$principalId'
      path: '/$principalId'
      fullPath: '/admin/staff/$principalId'
      preLoaderRoute: typeof AdminStaffPrincipalIdRouteImport
      parentRoute: typeof AdminStaffRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminStaffRouteChildren {
  AdminStaffPrincipalIdRoute: typeof AdminStaffPrincipalIdRoute
}

const AdminStaffRouteChildren: AdminStaffRouteChildren = {
  AdminStaffPrincipalIdRoute: AdminStaffPrincipalIdRoute,
}

const AdminStaffRouteWithChildren = AdminStaffRoute._addFileChildren(
  AdminStaffRouteChildren,
)

interface AdminRouteChildren {
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminStaffRoute: typeof AdminStaffRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminStaffRoute: AdminStaffRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthProfileSetupRoute: typeof AuthProfileSetupRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthUpdatePasswordRoute: typeof AuthUpdatePasswordRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthProfileSetupRoute: AuthProfileSetupRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthUpdatePasswordRoute: AuthUpdatePasswordRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface FantasyLeaguesRouteChildren {
  FantasyLeaguesLeagueIdRoute: typeof FantasyLeaguesLeagueIdRoute
}

const FantasyLeaguesRouteChildren: FantasyLeaguesRouteChildren = {
  FantasyLeaguesLeagueIdRoute: FantasyLeaguesLeagueIdRoute,
}

const FantasyLeaguesRouteWithChildren = FantasyLeaguesRoute._addFileChildren(
  FantasyLeaguesRouteChildren,
)

interface FantasyPlayersRouteChildren {
  FantasyPlayersPlayerIdRoute: typeof FantasyPlayersPlayerIdRoute
}

const FantasyPlayersRouteChildren: FantasyPlayersRouteChildren = {
  FantasyPlayersPlayerIdRoute: FantasyPlayersPlayerIdRoute,
}

const FantasyPlayersRouteWithChildren = FantasyPlayersRoute._addFileChildren(
  FantasyPlayersRouteChildren,
)

interface FantasyRouteChildren {
  FantasyCreateRoute: typeof FantasyCreateRoute
  FantasyFixturesRoute: typeof FantasyFixturesRoute
  FantasyLeaguesRoute: typeof FantasyLeaguesRouteWithChildren
  FantasyPlayersRoute: typeof FantasyPlayersRouteWithChildren
  FantasyPointsRoute: typeof FantasyPointsRoute
  FantasyRulesRoute: typeof FantasyRulesRoute
  FantasyTeamRoute: typeof FantasyTeamRoute
  FantasyTopPlayersRoute: typeof FantasyTopPlayersRoute
  FantasyTransfersRoute: typeof FantasyTransfersRoute
  FantasyIndexRoute: typeof FantasyIndexRoute
}

const FantasyRouteChildren: FantasyRouteChildren = {
  FantasyCreateRoute: FantasyCreateRoute,
  FantasyFixturesRoute: FantasyFixturesRoute,
  FantasyLeaguesRoute: FantasyLeaguesRouteWithChildren,
  FantasyPlayersRoute: FantasyPlayersRouteWithChildren,
  FantasyPointsRoute: FantasyPointsRoute,
  FantasyRulesRoute: FantasyRulesRoute,
  FantasyTeamRoute: FantasyTeamRoute,
  FantasyTopPlayersRoute: FantasyTopPlayersRoute,
  FantasyTransfersRoute: FantasyTransfersRoute,
  FantasyIndexRoute: FantasyIndexRoute,
}

const FantasyRouteWithChildren =
  FantasyRoute._addFileChildren(FantasyRouteChildren)

interface MatchesRouteChildren {
  MatchesMatchIdRoute: typeof MatchesMatchIdRoute
}

const MatchesRouteChildren: MatchesRouteChildren = {
  MatchesMatchIdRoute: MatchesMatchIdRoute,
}

const MatchesRouteWithChildren =
  MatchesRoute._addFileChildren(MatchesRouteChildren)

interface NewsRouteChildren {
  NewsArticleIdRoute: typeof NewsArticleIdRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsArticleIdRoute: NewsArticleIdRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  FantasyRoute: FantasyRouteWithChildren,
  MatchesRoute: MatchesRouteWithChildren,
  McpRoute: McpRoute,
  NewsRoute: NewsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
