// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

/**
 * How long a data request (PostgREST, `/rest/v1/`) may take before the app
 * gives up on it. The database cancels its own statements after 3 s for a
 * visitor and 8 s for a signed-in user, so this only fires when the network
 * or the platform hangs -- which on 2026-09-24 left pages on loading
 * skeletons for a minute or more. Auth and storage requests are left alone:
 * a sign-up can legitimately wait on the e-mail provider.
 */
export const REST_REQUEST_TIMEOUT_MS = 10_000;

function requestUrl(input: RequestInfo | URL): string {
  if (typeof input === "string") return input;
  if (input instanceof URL) return input.href;
  return input.url;
}

function withTimeout(signal: AbortSignal | null | undefined, timeoutMs: number) {
  if (typeof AbortSignal === "undefined" || typeof AbortSignal.timeout !== "function") {
    return signal ?? undefined;
  }
  const timeout = AbortSignal.timeout(timeoutMs);
  if (!signal) return timeout;
  // Keep the caller's own cancellation; add the deadline where the browser can.
  return typeof AbortSignal.any === "function" ? AbortSignal.any([signal, timeout]) : signal;
}

export function createSupabaseFetch(
  supabaseKey: string,
  {
    fetchImpl = (input, init) => fetch(input, init),
    timeoutMs = REST_REQUEST_TIMEOUT_MS,
  }: { fetchImpl?: typeof fetch; timeoutMs?: number } = {},
): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    if (!requestUrl(input).includes("/rest/v1/")) return fetchImpl(input, { ...init, headers });
    return fetchImpl(input, { ...init, headers, signal: withTimeout(init?.signal, timeoutMs) });
  };
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      // No `storage` on purpose. auth-js picks `localStorage` itself where the
      // browser allows it (its probe reads and writes inside a try/catch), and
      // keeps the session in memory where it does not: a server runtime, a
      // test's partial `window`, or a browser blocking site data. Handing it
      // `localStorage` from here meant reading that global unguarded, which
      // throws in that last case, so the client was never created and the
      // whole app fell to the error screen on start-up.
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
