import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";

/**
 * `apply-20260924-launch-fixes.sql` is the guarded script the owner runs in
 * the Supabase SQL editor to apply the 2026-09-24 launch-fix migrations to
 * production. It is generated by `assemble-apply-launch-fixes.py`; this test
 * re-assembles it the same way and fails when the committed script drifts
 * from its templates or from a migration file, when a migration is not
 * carried verbatim, or when it would ship as anything but a rehearsal.
 */

const root = join(import.meta.dir, "../..");
const read = (path: string) => readFileSync(join(root, path), "utf8");
const script = read("scripts/backend/apply-20260924-launch-fixes.sql");
const assembler = read("scripts/backend/assemble-apply-launch-fixes.py");

const batch = [...assembler.matchAll(/^\s+"(\d{14}_[a-z0-9_]+)",$/gm)].map((match) => match[1]);

function assemble(): string {
  const versions = batch.map((name) => name.split("_")[0]);
  let out = read("scripts/backend/templates/apply-launch-fixes.head.sql").replace(
    "@@BATCH_VERSIONS@@",
    versions.join(","),
  );
  for (const name of batch) {
    const version = name.slice(0, 14);
    const label = name.slice(15);
    const body = read(`supabase/migrations/${name}.sql`);
    const tag = `$bg_${version}_file$`;
    out +=
      "-- ---------------------------------------------------------------------------\n" +
      `-- Migration ${name}, exactly as in the repository\n` +
      "-- ---------------------------------------------------------------------------\n" +
      body +
      "\ninsert into supabase_migrations.schema_migrations (version, name, statements)\n" +
      `values (\n  '${version}',\n  '${label}',\n  array[${tag}${body}${tag}]\n);\n\n`;
  }
  return out + read("scripts/backend/templates/apply-launch-fixes.tail.sql");
}

function occurrences(haystack: string, needle: string): number {
  return haystack.split(needle).length - 1;
}

describe("the production apply script for the 2026-09-24 launch fixes", () => {
  test("names at least the Fantasy postponement migration", () => {
    expect(batch).toContain("20260924200000_fantasy_postponement_and_enrolment");
  });

  test("is exactly what the assembler produces from its sources", () => {
    expect(script).toBe(assemble());
  });

  test("carries every migration verbatim, once to run and once to record", () => {
    for (const name of batch) {
      const body = read(`supabase/migrations/${name}.sql`);
      expect({ name, occurrences: occurrences(script, body) }).toEqual({ name, occurrences: 2 });
    }
  });

  test("ships as a rehearsal that cannot commit unless the MODE line is changed", () => {
    expect(
      occurrences(script, "select set_config('botolago.launch_fixes_mode', 'REHEARSAL', true);"),
    ).toBe(1);
    expect(script).not.toContain("'APPLY', true);");
    expect(script).toContain("REHEARSAL PASSED -- nothing was saved.");
    // The raise sits before the only commit.
    expect(script.indexOf("REHEARSAL PASSED")).toBeLessThan(script.indexOf("\ncommit;"));
    expect(occurrences(script, "\ncommit;")).toBe(1);
  });

  test("bounds its locks and runs every guard before the first write", () => {
    const firstMigration = script.indexOf("-- Migration ");
    for (const guard of [
      "set local lock_timeout = '5s';",
      "set local statement_timeout = '120s';",
      "part of this batch is already recorded as applied",
      "this batch was built on 20260924190100",
      "changed since review",
    ]) {
      const at = script.indexOf(guard);
      expect({ guard, beforeFirstWrite: at !== -1 && at < firstMigration }).toEqual({
        guard,
        beforeFirstWrite: true,
      });
    }
  });
});
