/**
 * Builds the frozen bulk-mapping manifest from the output of the READ-ONLY
 * `football-mapping-bulk-manifest.sql` (its `manifest_rows` json document).
 *
 *   bun scripts/backend/build-bulk-mapping-manifest.ts <manifest_rows.json> [YYYY-MM-DD]
 *
 * Writes the committed review artifacts:
 *   docs/production/manifests/player-mapping-bulk-<date>.manifest.json
 *   docs/production/manifests/player-mapping-bulk-<date>.manifest.sha256
 *   src/components/admin/player-mappings/bulk-manifest.ts   (what the screen verifies and uses)
 *
 * Refuses a row that does not meet the frozen contract, and re-verifies the whole
 * manifest (hash, order, no duplicate candidate / provider id / target, no name,
 * no date) before writing anything. It reads no database and writes no database.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { BULK_REASONS } from "../../src/backend/football/identity/bulk-mapping/contract";
import {
  buildManifest,
  verifyManifest,
  type ManifestRow,
} from "../../src/backend/football/identity/bulk-mapping/manifest";

const [input, date = new Date().toISOString().slice(0, 10)] = process.argv.slice(2);
if (!input) throw new Error("usage: build-bulk-mapping-manifest.ts <manifest_rows.json> [date]");
const root = join(import.meta.dir, "../..");

interface SqlRow {
  candidateId: string;
  externalId: string;
  appPlayerId: string;
  appTeamId: string;
  evidenceRevision: number;
  tier: "A" | "B";
  shirt: "match" | "no_signal";
  evidence: Record<string, unknown>;
  signals: { sofascore: Record<string, unknown> };
  reason: string;
  expectedFingerprint: string;
}
const document = JSON.parse(readFileSync(input, "utf8")) as { summary: unknown; rows: SqlRow[] };

const rows: ManifestRow[] = document.rows.map((r) => {
  const s = r.signals.sofascore;
  const flags = Array.isArray(s.flags) ? s.flags : [-1];
  if (
    s.dob !== "match" ||
    s.position !== "match" ||
    s.club !== "match" ||
    flags.length !== 0 ||
    s.observationCount !== 1 ||
    r.reason !== BULK_REASONS[r.tier] ||
    (r.tier === "A") !== (r.shirt === "match")
  )
    throw new Error(`row ${r.candidateId} does not meet the frozen contract`);
  return {
    candidateId: r.candidateId,
    provider: "sofascore",
    externalId: r.externalId,
    appPlayerId: r.appPlayerId,
    appTeamId: r.appTeamId,
    evidenceRevision: r.evidenceRevision,
    tier: r.tier,
    candidateStatus: "unmapped",
    currentMappingState: "none",
    openProposalState: "none",
    observationCount: 1,
    squadCompleteness: "COMPLETE",
    signals: { dob: "match", position: "match", club: "match", shirt: r.shirt },
    sportsMonksCorroboration: true,
    fingerprintInputs: {
      kind: "map",
      basis: "manual",
      sofascoreCandidateId: r.candidateId,
      sofascoreExternalId: r.externalId,
      appPlayerId: r.appPlayerId,
      candidateRevisions: { sofascore: r.evidenceRevision },
      evidence: r.evidence,
      signals: r.signals,
      positionDisagreement: false,
    },
    expectedFingerprint: r.expectedFingerprint,
  };
});

const manifest = await buildManifest(rows);
const verdict = await verifyManifest(JSON.parse(JSON.stringify(manifest)));
if (!verdict.ok)
  throw new Error(`the manifest failed verification: ${verdict.problems.join("; ")}`);

const name = `player-mapping-bulk-${date}`;
const dir = join(root, "docs/production/manifests");
mkdirSync(dir, { recursive: true });
const json = `${JSON.stringify(manifest, null, 2)}\n`;
writeFileSync(join(dir, `${name}.manifest.json`), json);
writeFileSync(
  join(dir, `${name}.manifest.sha256`),
  `${manifest.manifestSha256}  ${name}.manifest.json (canonical-manifest SHA-256, see docs)\n`,
);
writeFileSync(
  join(root, "src/components/admin/player-mappings/bulk-manifest.ts"),
  `/**
 * The frozen, reviewed production manifest of the controlled bulk batch, generated by
 * scripts/backend/build-bulk-mapping-manifest.ts from the read-only eligibility query and
 * committed as a reviewed production artifact (see docs/production/manifests). The screen
 * verifies its SHA-256 and shape before offering anything. Do not edit by hand.
 */
export const BULK_MANIFEST: unknown = ${JSON.stringify(manifest)};
`,
);
console.log(
  JSON.stringify({
    rows: manifest.rows.length,
    population: manifest.population,
    sha256: manifest.manifestSha256,
  }),
);
